// =======================================================
//  VicAI Mini AI Engine (V1)
//  Lightweight, safe, Cloudflare-compatible AI logic
// =======================================================

import { securityCheck } from "./security.js";

// -------------------------------------------------------
//  CLASSIFIER — detect what type of request user made
// -------------------------------------------------------
function classifyInput(text) {
  const lower = text.toLowerCase();

  // Code request
  if (
    lower.includes("code") ||
    lower.includes("write a function") ||
    lower.includes("make me a script") ||
    lower.includes("javascript") ||
    lower.includes("python")
  ) {
    return "code";
  }

  // Teaching request
  if (
    lower.includes("explain") ||
    lower.includes("teach me") ||
    lower.includes("how does") ||
    lower.includes("what is")
  ) {
    return "teach";
  }

  // Normal conversation
  return "chat";
}

// -------------------------------------------------------
//  CHAT RESPONSE GENERATOR
// -------------------------------------------------------
function chatResponse(text) {
  return [
    "Gotchu! 😎 Here's what I think:",
    "Alright bet, here's the breakdown:",
    "Okay I hear you — check this out:",
    "Sure thing! Here's my take:"
  ][Math.floor(Math.random() * 4)] + "\n\n" +
  generateFriendly(text);
}

// Friendly style
function generateFriendly(text) {
  return (
    "So basically, **" +
    text.replace(/[^a-zA-Z0-9 ]/g, "").slice(0, 200) +
    "** — here's my understanding:\n\n" +
    "• You're trying to figure something out.\n" +
    "• You're asking in a casual way.\n" +
    "• I gotchu, let's solve it together. 😄"
  );
}

// -------------------------------------------------------
//  CODE RESPONSE GENERATOR
// -------------------------------------------------------
function codeResponse(text) {
  // Basic template for clean consistent code replies
  return `
Here’s the code you asked for 🚀

\`\`\`js
// Auto-generated by VicAI Engine
// Input: ${text}

function example() {
  return "This is a placeholder code example.";
}
\`\`\`

If you want it in another language, ask me!
`;
}

// -------------------------------------------------------
//  TEACHING RESPONSE GENERATOR
// -------------------------------------------------------
function teachResponse(text) {
  return `
Alright let me explain it in simple terms 👇

**${text}** means:

1. I break it down to the basics  
2. I remove confusing stuff  
3. I give you the easiest version possible  

If you want a deeper explanation or examples, just say **"go deeper"** 🔍
`;
}

// -------------------------------------------------------
//  MAIN AI ENGINE EXPORT
// -------------------------------------------------------
export function runAI(userInput) {
  // Step 1: security check
  const safety = securityCheck(userInput);

  if (!safety.allowed) {
    return {
      ok: false,
      reason: safety.reason,
      response: "❌ Request blocked for safety: " + safety.reason
    };
  }

  const clean = safety.sanitizedInput;
  const type = classifyInput(clean);

  // Step 2: generate response based on classification
  if (type === "code") {
    return {
      ok: true,
      type,
      response: codeResponse(clean)
    };
  }

  if (type === "teach") {
    return {
      ok: true,
      type,
      response: teachResponse(clean)
    };
  }

  // Default: chat mode
  return {
    ok: true,
    type,
    response: chatResponse(clean)
  };
}
